### PR TITLE
Drop ruby 1.9.3, add testing on 2.3.0 & 2.4.1

### PR DESCRIPTION
**Pull request by Evesy**
## Pull Request Checklist

RE https://github.com/sensu-plugins/sensu-plugins-feature-requests/issues/27

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose

Drop 1.9.3 support
Add testing on 2.3.0 & 2.4.1

#### Known Compatablity Issues

Breaking change for any users on Ruby 1.9.3

### CODE REVIEW

**Comment by Evesy** [comment]
Builds failing on 2.0 & 2.1 due to a transitive dependency on Mustermann gem, which requires a Ruby 2.2 implementation to run.

**Comment by Evesy** [comment]
Similar story with 2.2 -- Sinatra has the following dependency on rack: `~> 2.0`; Rack 2.0.3 requires Ruby 2.2.2

**Comment by majormoses** [comment]
You would need to pin the dependencies to this: https://rubygems.org/gems/mustermann/versions/0.4.0 which I am not in favor of. As ruby 2.1 is EOL and our alternative is to support either 4 year old code or new code I vote new code takes priority here. Lets make this a break all the things release. We do want to do real runtime testing before doing this though.

**Comment by majormoses** [comment]
@Evesy as we have officially changed our stance on supported ruby versions inline with my suggestion to just drop ruby less than ruby 2.2.2

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-resque/versions/1.0.0

**Pull request merged**
